"use client";

/**
 * This configuration is used to for the Sanity Studio that’s mounted on the `/app/admin/[[...tool]]/page.tsx` route
 */

import { visionTool } from "@sanity/vision";
import { defineConfig } from "sanity";
import { structureTool } from "sanity/structure";
import { muxInput } from "sanity-plugin-mux-input";

// Go to https://www.sanity.io/docs/api-versioning to learn how API versioning works
import { apiVersion, dataset, projectId } from "./sanity/env";
import { schemas } from "./sanity/schemaTypes";
import { structure } from "./sanity/structure";

export default defineConfig({
  basePath: "/admin",
  projectId,
  dataset,
  name: "default",
  title: "Recording Alchemy LMS",

  // Add and edit the content schema in the './sanity/schemaTypes' folder
  schema: { types: schemas },
  plugins: [
    structureTool({ structure }),
    // Vision is for querying with GROQ from inside the Studio
    // https://www.sanity.io/docs/the-vision-plugin
    muxInput({
      mp4_support: "standard",
      max_resolution_tier: "2160p",
      encoding_tier: "smart",
      defaultAutogeneratedSubtitleLang: "en",
    }),
    visionTool({ defaultApiVersion: apiVersion }),
  ],
});
